//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMM03500FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LMM03500FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LMM03500FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMM03500FrontResources.LMM03500FrontResources_msgrsc", typeof(LMM03500FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string _AccountNo {
            get {
                return ResourceManager.GetString("_AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string _Address {
            get {
                return ResourceManager.GetString("_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement List.
        /// </summary>
        internal static string _AgreementList {
            get {
                return ResourceManager.GetString("_AgreementList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention 1.
        /// </summary>
        internal static string _Attention1 {
            get {
                return ResourceManager.GetString("_Attention1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention 2.
        /// </summary>
        internal static string _Attention2 {
            get {
                return ResourceManager.GetString("_Attention2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention Name.
        /// </summary>
        internal static string _AttentionName {
            get {
                return ResourceManager.GetString("_AttentionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string _Bank {
            get {
                return ResourceManager.GetString("_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Code.
        /// </summary>
        internal static string _BankCode {
            get {
                return ResourceManager.GetString("_BankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Id.
        /// </summary>
        internal static string _BankId {
            get {
                return ResourceManager.GetString("_BankId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string _BankName {
            get {
                return ResourceManager.GetString("_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing.
        /// </summary>
        internal static string _Billing {
            get {
                return ResourceManager.GetString("_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillingTo.
        /// </summary>
        internal static string _BillingTo {
            get {
                return ResourceManager.GetString("_BillingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string _BirthDate {
            get {
                return ResourceManager.GetString("_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdays.
        /// </summary>
        internal static string _Birthdays {
            get {
                return ResourceManager.GetString("_Birthdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string _City {
            get {
                return ResourceManager.GetString("_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification.
        /// </summary>
        internal static string _Classification {
            get {
                return ResourceManager.GetString("_Classification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classififcation.
        /// </summary>
        internal static string _Classififcation {
            get {
                return ResourceManager.GetString("_Classififcation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string _Country {
            get {
                return ResourceManager.GetString("_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreatedDate {
            get {
                return ResourceManager.GetString("_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string _Currency {
            get {
                return ResourceManager.GetString("_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _Date {
            get {
                return ResourceManager.GetString("_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string _Email {
            get {
                return ResourceManager.GetString("_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Card.
        /// </summary>
        internal static string _FamilyCard {
            get {
                return ResourceManager.GetString("_FamilyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Card (KK).
        /// </summary>
        internal static string _FamilyCard_KK_ {
            get {
                return ResourceManager.GetString("_FamilyCard(KK)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix VA.
        /// </summary>
        internal static string _FixVA {
            get {
                return ResourceManager.GetString("_FixVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string _FullName {
            get {
                return ResourceManager.GetString("_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string _Gender {
            get {
                return ResourceManager.GetString("_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string _Id {
            get {
                return ResourceManager.GetString("_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Expired Date.
        /// </summary>
        internal static string _IDExpiredDate {
            get {
                return ResourceManager.GetString("_IDExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID No.
        /// </summary>
        internal static string _IDNo {
            get {
                return ResourceManager.GetString("_IDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number.
        /// </summary>
        internal static string _IDNumber {
            get {
                return ResourceManager.GetString("_IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type.
        /// </summary>
        internal static string _IDType {
            get {
                return ResourceManager.GetString("_IDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string _Invalid {
            get {
                return ResourceManager.GetString("_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group.
        /// </summary>
        internal static string _JournalGroup {
            get {
                return ResourceManager.GetString("_JournalGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Amount.
        /// </summary>
        internal static string _LimitAmount {
            get {
                return ResourceManager.GetString("_LimitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of Business.
        /// </summary>
        internal static string _LineofBusiness {
            get {
                return ResourceManager.GetString("_LineofBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string _List {
            get {
                return ResourceManager.GetString("_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string _Members {
            get {
                return ResourceManager.GetString("_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        internal static string _MobileNo {
            get {
                return ResourceManager.GetString("_MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No (1).
        /// </summary>
        internal static string _MobileNo_1_ {
            get {
                return ResourceManager.GetString("_MobileNo(1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No (2).
        /// </summary>
        internal static string _MobileNo_2_ {
            get {
                return ResourceManager.GetString("_MobileNo(2)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string _Name {
            get {
                return ResourceManager.GetString("_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        internal static string _Nationality {
            get {
                return ResourceManager.GetString("_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string _Next {
            get {
                return ResourceManager.GetString("_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _Notes {
            get {
                return ResourceManager.GetString("_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _OK {
            get {
                return ResourceManager.GetString("_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        internal static string _Overwrite {
            get {
                return ResourceManager.GetString("_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Term.
        /// </summary>
        internal static string _PaymentTerm {
            get {
                return ResourceManager.GetString("_PaymentTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1.
        /// </summary>
        internal static string _Phone1 {
            get {
                return ResourceManager.GetString("_Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No (1).
        /// </summary>
        internal static string _PhoneNo_1_ {
            get {
                return ResourceManager.GetString("_PhoneNo(1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No (2).
        /// </summary>
        internal static string _PhoneNo_2_ {
            get {
                return ResourceManager.GetString("_PhoneNo(2)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No 1.
        /// </summary>
        internal static string _PhoneNo1 {
            get {
                return ResourceManager.GetString("_PhoneNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No 2.
        /// </summary>
        internal static string _PhoneNo2 {
            get {
                return ResourceManager.GetString("_PhoneNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string _Position {
            get {
                return ResourceManager.GetString("_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Payment with Withholding Tax(PPh) Deduction.
        /// </summary>
        internal static string _PPh {
            get {
                return ResourceManager.GetString("_PPh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processs.
        /// </summary>
        internal static string _Process {
            get {
                return ResourceManager.GetString("_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string _Profile {
            get {
                return ResourceManager.GetString("_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTY.
        /// </summary>
        internal static string _Property2 {
            get {
                return ResourceManager.GetString("_Property2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string _Province {
            get {
                return ResourceManager.GetString("_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        internal static string _Relationship {
            get {
                return ResourceManager.GetString("_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman.
        /// </summary>
        internal static string _Salesman {
            get {
                return ResourceManager.GetString("_Salesman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to Excel.
        /// </summary>
        internal static string _SavetoExcel {
            get {
                return ResourceManager.GetString("_SavetoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence No.
        /// </summary>
        internal static string _SequenceNo {
            get {
                return ResourceManager.GetString("_SequenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File.
        /// </summary>
        internal static string _SourceFile {
            get {
                return ResourceManager.GetString("_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        internal static string _TaxCode {
            get {
                return ResourceManager.GetString("_TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id.
        /// </summary>
        internal static string _TaxId {
            get {
                return ResourceManager.GetString("_TaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Info.
        /// </summary>
        internal static string _TaxInfo {
            get {
                return ResourceManager.GetString("_TaxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name.
        /// </summary>
        internal static string _TaxName {
            get {
                return ResourceManager.GetString("_TaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Type.
        /// </summary>
        internal static string _TaxType {
            get {
                return ResourceManager.GetString("_TaxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string _Template {
            get {
                return ResourceManager.GetString("_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        internal static string _Tenant {
            get {
                return ResourceManager.GetString("_Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Category.
        /// </summary>
        internal static string _TenantCategory {
            get {
                return ResourceManager.GetString("_TenantCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Group.
        /// </summary>
        internal static string _TenantGroup {
            get {
                return ResourceManager.GetString("_TenantGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Id.
        /// </summary>
        internal static string _TenantId {
            get {
                return ResourceManager.GetString("_TenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        internal static string _TenantName {
            get {
                return ResourceManager.GetString("_TenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Type.
        /// </summary>
        internal static string _TenantType {
            get {
                return ResourceManager.GetString("_TenantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Row(s).
        /// </summary>
        internal static string _TotalRows {
            get {
                return ResourceManager.GetString("_TotalRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit 1.
        /// </summary>
        internal static string _Unit1 {
            get {
                return ResourceManager.GetString("_Unit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string _Units {
            get {
                return ResourceManager.GetString("_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdatedBy {
            get {
                return ResourceManager.GetString("_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdatedDate {
            get {
                return ResourceManager.GetString("_UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string _Upload {
            get {
                return ResourceManager.GetString("_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VA Code.
        /// </summary>
        internal static string _VACode {
            get {
                return ResourceManager.GetString("_VACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string _Valid {
            get {
                return ResourceManager.GetString("_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string _ZipCode {
            get {
                return ResourceManager.GetString("_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure download this template?.
        /// </summary>
        internal static string M001 {
            get {
                return ResourceManager.GetString("M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Successfully.
        /// </summary>
        internal static string M002 {
            get {
                return ResourceManager.GetString("M002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type must Microsoft Excel .xlsx.
        /// </summary>
        internal static string M003 {
            get {
                return ResourceManager.GetString("M003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is Empty.
        /// </summary>
        internal static string M004 {
            get {
                return ResourceManager.GetString("M004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure want process these records?.
        /// </summary>
        internal static string M005 {
            get {
                return ResourceManager.GetString("M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Profile&apos;s Tenant ID is required.
        /// </summary>
        internal static string V001 {
            get {
                return ResourceManager.GetString("V001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Profile&apos;s Address is required.
        /// </summary>
        internal static string V002 {
            get {
                return ResourceManager.GetString("V002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Profile&apos;s Tenant Category is required.
        /// </summary>
        internal static string V003 {
            get {
                return ResourceManager.GetString("V003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Profile&apos;s Tenant Type is required.
        /// </summary>
        internal static string V004 {
            get {
                return ResourceManager.GetString("V004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Profile&apos;s Tenant Name is required.
        /// </summary>
        internal static string V005 {
            get {
                return ResourceManager.GetString("V005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Profile&apos;s Journal Group is required.
        /// </summary>
        internal static string V006 {
            get {
                return ResourceManager.GetString("V006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Profile&apos;s Payment Term is required.
        /// </summary>
        internal static string V007 {
            get {
                return ResourceManager.GetString("V007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Profile&apos;s Currency is required.
        /// </summary>
        internal static string V008 {
            get {
                return ResourceManager.GetString("V008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Profile&apos;s Salesman is required.
        /// </summary>
        internal static string V009 {
            get {
                return ResourceManager.GetString("V009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Profile&apos;s Line Of Business is required.
        /// </summary>
        internal static string V010 {
            get {
                return ResourceManager.GetString("V010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing To is required.
        /// </summary>
        internal static string V011 {
            get {
                return ResourceManager.GetString("V011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address is required.
        /// </summary>
        internal static string V012 {
            get {
                return ResourceManager.GetString("V012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name is required.
        /// </summary>
        internal static string V013 {
            get {
                return ResourceManager.GetString("V013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is required.
        /// </summary>
        internal static string V014 {
            get {
                return ResourceManager.GetString("V014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date is required.
        /// </summary>
        internal static string V015 {
            get {
                return ResourceManager.GetString("V015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type is required.
        /// </summary>
        internal static string V016 {
            get {
                return ResourceManager.GetString("V016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID No is required.
        /// </summary>
        internal static string V017 {
            get {
                return ResourceManager.GetString("V017", resourceCulture);
            }
        }
    }
}
