//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM09300FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GSM09300FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GSM09300FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSM09300FrontResources.GSM09300FrontResources_msgrsc", typeof(GSM09300FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Code*.
        /// </summary>
        internal static string _CategoryCode {
            get {
                return ResourceManager.GetString("_CategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name*.
        /// </summary>
        internal static string _CategoryName {
            get {
                return ResourceManager.GetString("_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreatedDate {
            get {
                return ResourceManager.GetString("_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _Date {
            get {
                return ResourceManager.GetString("_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string _Email {
            get {
                return ResourceManager.GetString("_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Supplier Category.
        /// </summary>
        internal static string _FromSupplierCategory {
            get {
                return ResourceManager.GetString("_FromSupplierCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level*.
        /// </summary>
        internal static string _Level {
            get {
                return ResourceManager.GetString("_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string _Move {
            get {
                return ResourceManager.GetString("_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _Notes {
            get {
                return ResourceManager.GetString("_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _OK {
            get {
                return ResourceManager.GetString("_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category*.
        /// </summary>
        internal static string _ParentCategory {
            get {
                return ResourceManager.GetString("_ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1.
        /// </summary>
        internal static string _Phone1 {
            get {
                return ResourceManager.GetString("_Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _Process {
            get {
                return ResourceManager.GetString("_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTY.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Category.
        /// </summary>
        internal static string _SupplierCategory {
            get {
                return ResourceManager.GetString("_SupplierCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Category Id.
        /// </summary>
        internal static string _SupplierCategoryId {
            get {
                return ResourceManager.GetString("_SupplierCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Category Name.
        /// </summary>
        internal static string _SupplierCategoryName {
            get {
                return ResourceManager.GetString("_SupplierCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Group.
        /// </summary>
        internal static string _SupplierGroup {
            get {
                return ResourceManager.GetString("_SupplierGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Id.
        /// </summary>
        internal static string _SupplierId {
            get {
                return ResourceManager.GetString("_SupplierId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier List.
        /// </summary>
        internal static string _SupplierList {
            get {
                return ResourceManager.GetString("_SupplierList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        internal static string _SupplierName {
            get {
                return ResourceManager.GetString("_SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Type.
        /// </summary>
        internal static string _SupplierType {
            get {
                return ResourceManager.GetString("_SupplierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Supplier Category.
        /// </summary>
        internal static string _ToSupplierCategory {
            get {
                return ResourceManager.GetString("_ToSupplierCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string _Units {
            get {
                return ResourceManager.GetString("_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdatedBy {
            get {
                return ResourceManager.GetString("_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdatedDate {
            get {
                return ResourceManager.GetString("_UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Supplier Category cannot be same as From Supplier Category.
        /// </summary>
        internal static string M001 {
            get {
                return ResourceManager.GetString("M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Code is required.
        /// </summary>
        internal static string V001 {
            get {
                return ResourceManager.GetString("V001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name is required.
        /// </summary>
        internal static string V002 {
            get {
                return ResourceManager.GetString("V002", resourceCulture);
            }
        }
    }
}
