using System;
using System.Collections.Generic;
using System.Text;

namespace GSM09000COMMON
{
    public class ContextConstant
    {
        public const string GSM09000_PROPERTY_ID_STREAMING_CONTEXT = "GSM09000_PROPERTY_ID_STREAMING_CONTEXT";
        public const string GSM09000_PROPERTY_ID_CONTEXT = "GSM09000_PROPERTY_ID_CONTEXT";

        public const string LMM03001_PROPERTY_ID_STREAMING_CONTEXT = "LMM03001_PROPERTY_ID_STREAMING_CONTEXT";
        public const string LMM03001_FROM_TENANT_CATEGORY_ID_STREAMING_CONTEXT = "LMM03001_FROM_TENANT_CATEGORY_ID_STREAMING_CONTEXT";
        public const string LMM03001_PROPERTY_ID_CONTEXT = "LMM03001_PROPERTY_ID_CONTEXT";
        public const string LMM03001_TENANT_CATEGORY_ID_CONTEXT = "LMM03001_TENANT_CATEGORY_ID_CONTEXT";
        public const string LMM03001_FROM_TENANT_CATEGORY_ID_CONTEXT = "LMM03001_FROM_TENANT_CATEGORY_ID_CONTEXT";
        public const string LMM03001_TENANT_ID_CONTEXT = "LMM03001_TENANT_ID_CONTEXT";
        public const string LMM03001_TO_TENANT_CATEGORY_ID_CONTEXT = "LMM03001_TO_TENANT_CATEGORY_ID_CONTEXT";
    }
}
