//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APM00200FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APM00200FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APM00200FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APM00200FrontResources.APM00200FrontResources_msgrsc", typeof(APM00200FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string _Activate {
            get {
                return ResourceManager.GetString("_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category*.
        /// </summary>
        internal static string _Category {
            get {
                return ResourceManager.GetString("_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        internal static string _CategoryID {
            get {
                return ResourceManager.GetString("_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        internal static string _ChooseFile {
            get {
                return ResourceManager.GetString("_ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy From.
        /// </summary>
        internal static string _CopyFrom {
            get {
                return ResourceManager.GetString("_CopyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string _Deactivate {
            get {
                return ResourceManager.GetString("_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Description {
            get {
                return ResourceManager.GetString("_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string _Detail {
            get {
                return ResourceManager.GetString("_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure ID.
        /// </summary>
        internal static string _ExpenditureID {
            get {
                return ResourceManager.GetString("_ExpenditureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure Name.
        /// </summary>
        internal static string _ExpenditureName {
            get {
                return ResourceManager.GetString("_ExpenditureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string _Invalid {
            get {
                return ResourceManager.GetString("_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group*.
        /// </summary>
        internal static string _JournalGroup {
            get {
                return ResourceManager.GetString("_JournalGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group ID.
        /// </summary>
        internal static string _JournalGroupID {
            get {
                return ResourceManager.GetString("_JournalGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _Notes {
            get {
                return ResourceManager.GetString("_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _OK {
            get {
                return ResourceManager.GetString("_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Tax.
        /// </summary>
        internal static string _OtherTax {
            get {
                return ResourceManager.GetString("_OtherTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procees.
        /// </summary>
        internal static string _Process {
            get {
                return ResourceManager.GetString("_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string _Property {
            get {
                return ResourceManager.GetString("_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string _Refresh {
            get {
                return ResourceManager.GetString("_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To Excel.
        /// </summary>
        internal static string _SaveToExcel {
            get {
                return ResourceManager.GetString("_SaveToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File.
        /// </summary>
        internal static string _SourceFile {
            get {
                return ResourceManager.GetString("_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable.
        /// </summary>
        internal static string _Taxable {
            get {
                return ResourceManager.GetString("_Taxable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        internal static string _TaxID {
            get {
                return ResourceManager.GetString("_TaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Type.
        /// </summary>
        internal static string _TaxType {
            get {
                return ResourceManager.GetString("_TaxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string _Template {
            get {
                return ResourceManager.GetString("_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Row(s).
        /// </summary>
        internal static string _TotalRows {
            get {
                return ResourceManager.GetString("_TotalRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string _Unit {
            get {
                return ResourceManager.GetString("_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdatedBy {
            get {
                return ResourceManager.GetString("_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string _Upload {
            get {
                return ResourceManager.GetString("_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string _Valid {
            get {
                return ResourceManager.GetString("_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withholding Tax.
        /// </summary>
        internal static string _WithholdingTax {
            get {
                return ResourceManager.GetString("_WithholdingTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to {0} this Expenditure?.
        /// </summary>
        internal static string M001 {
            get {
                return ResourceManager.GetString("M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Expenditure Successful!.
        /// </summary>
        internal static string M002 {
            get {
                return ResourceManager.GetString("M002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure download this template?.
        /// </summary>
        internal static string M003 {
            get {
                return ResourceManager.GetString("M003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type must Microsoft Excel .xlsx.
        /// </summary>
        internal static string M004 {
            get {
                return ResourceManager.GetString("M004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is Empty.
        /// </summary>
        internal static string M005 {
            get {
                return ResourceManager.GetString("M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure want process these records?.
        /// </summary>
        internal static string M006 {
            get {
                return ResourceManager.GetString("M006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Successfully.
        /// </summary>
        internal static string M007 {
            get {
                return ResourceManager.GetString("M007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure Code is required!.
        /// </summary>
        internal static string V001 {
            get {
                return ResourceManager.GetString("V001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenditure Name is required!.
        /// </summary>
        internal static string V002 {
            get {
                return ResourceManager.GetString("V002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category is required!.
        /// </summary>
        internal static string V003 {
            get {
                return ResourceManager.GetString("V003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit is required!.
        /// </summary>
        internal static string V004 {
            get {
                return ResourceManager.GetString("V004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withholding Tax Id is required!.
        /// </summary>
        internal static string V005 {
            get {
                return ResourceManager.GetString("V005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Tax Type!.
        /// </summary>
        internal static string V006 {
            get {
                return ResourceManager.GetString("V006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group is required!.
        /// </summary>
        internal static string V007 {
            get {
                return ResourceManager.GetString("V007", resourceCulture);
            }
        }
    }
}
