//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSM01500FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GSM01500FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GSM01500FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GSM01500FrontResources.GSM01500FrontResources_msgrsc", typeof(GSM01500FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string _Activate {
            get {
                return ResourceManager.GetString("_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string _Center {
            get {
                return ResourceManager.GetString("_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Code.
        /// </summary>
        internal static string _CenterCode {
            get {
                return ResourceManager.GetString("_CenterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name.
        /// </summary>
        internal static string _CenterName {
            get {
                return ResourceManager.GetString("_CenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centers.
        /// </summary>
        internal static string _Centers {
            get {
                return ResourceManager.GetString("_Centers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string _Close {
            get {
                return ResourceManager.GetString("_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string _Company {
            get {
                return ResourceManager.GetString("_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Id.
        /// </summary>
        internal static string _CompanyId {
            get {
                return ResourceManager.GetString("_CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string _CompanyName {
            get {
                return ResourceManager.GetString("_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy From.
        /// </summary>
        internal static string _CopyFrom {
            get {
                return ResourceManager.GetString("_CopyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreatedDate {
            get {
                return ResourceManager.GetString("_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _Department {
            get {
                return ResourceManager.GetString("_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        internal static string _DepartmentCode {
            get {
                return ResourceManager.GetString("_DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        internal static string _DepartmentName {
            get {
                return ResourceManager.GetString("_DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string _Inactive {
            get {
                return ResourceManager.GetString("_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string _Invalid {
            get {
                return ResourceManager.GetString("_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Active Date.
        /// </summary>
        internal static string _NonActiveDate {
            get {
                return ResourceManager.GetString("_NonActiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string _Notes {
            get {
                return ResourceManager.GetString("_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string _Print {
            get {
                return ResourceManager.GetString("_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Department.
        /// </summary>
        internal static string _PrintDepartment {
            get {
                return ResourceManager.GetString("_PrintDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Inactive Center.
        /// </summary>
        internal static string _PrintInactiveCenter {
            get {
                return ResourceManager.GetString("_PrintInactiveCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _Process {
            get {
                return ResourceManager.GetString("_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save To Excel.
        /// </summary>
        internal static string _SaveToExcel {
            get {
                return ResourceManager.GetString("_SaveToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File.
        /// </summary>
        internal static string _SourceFile {
            get {
                return ResourceManager.GetString("_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string _Template {
            get {
                return ResourceManager.GetString("_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Row(s).
        /// </summary>
        internal static string _TotalRows {
            get {
                return ResourceManager.GetString("_TotalRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdatedBy {
            get {
                return ResourceManager.GetString("_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdatedDate {
            get {
                return ResourceManager.GetString("_UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string _Upload {
            get {
                return ResourceManager.GetString("_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string _Valid {
            get {
                return ResourceManager.GetString("_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure download this template?.
        /// </summary>
        internal static string M001 {
            get {
                return ResourceManager.GetString("M001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centers From cannot be the same with Centers To.
        /// </summary>
        internal static string M002 {
            get {
                return ResourceManager.GetString("M002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centers To cannot be the same with Centers From.
        /// </summary>
        internal static string M003 {
            get {
                return ResourceManager.GetString("M003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Successfully.
        /// </summary>
        internal static string M004 {
            get {
                return ResourceManager.GetString("M004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type must Microsoft Excel .xlsx.
        /// </summary>
        internal static string M005 {
            get {
                return ResourceManager.GetString("M005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is Empty.
        /// </summary>
        internal static string M006 {
            get {
                return ResourceManager.GetString("M006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure want process these records?.
        /// </summary>
        internal static string M007 {
            get {
                return ResourceManager.GetString("M007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Code is required.
        /// </summary>
        internal static string V001 {
            get {
                return ResourceManager.GetString("V001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name is required.
        /// </summary>
        internal static string V002 {
            get {
                return ResourceManager.GetString("V002", resourceCulture);
            }
        }
    }
}
